/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BandwidthResultDTO
 */
export interface BandwidthResultDTO {
    /**
     * ID of the test result
     * @type {string}
     * @memberof BandwidthResultDTO
     */
    id: string;
    /**
     * ID of the tested node
     * @type {string}
     * @memberof BandwidthResultDTO
     */
    fromNodeId: string;
    /**
     * ID of the node
     * @type {string}
     * @memberof BandwidthResultDTO
     */
    toNodeId: string;
    /**
     * 
     * @type {string}
     * @memberof BandwidthResultDTO
     */
    entitySeed: string;
    /**
     * 
     * @type {string}
     * @memberof BandwidthResultDTO
     */
    entityHash: string;
    /**
     * 
     * @type {string}
     * @memberof BandwidthResultDTO
     */
    reportedHash: string;
    /**
     * 
     * @type {number}
     * @memberof BandwidthResultDTO
     */
    iterations: number;
    /**
     * 
     * @type {number}
     * @memberof BandwidthResultDTO
     */
    downloadTime: number;
    /**
     * 
     * @type {boolean}
     * @memberof BandwidthResultDTO
     */
    entityValid: boolean;
    /**
     * 
     * @type {number}
     * @memberof BandwidthResultDTO
     */
    round: number;
    /**
     * 
     * @type {number}
     * @memberof BandwidthResultDTO
     */
    speed: number;
    /**
     * 
     * @type {string}
     * @memberof BandwidthResultDTO
     */
    createdAt: string;
}

export function BandwidthResultDTOFromJSON(json: any): BandwidthResultDTO {
    return BandwidthResultDTOFromJSONTyped(json, false);
}

export function BandwidthResultDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BandwidthResultDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fromNodeId': json['fromNodeId'],
        'toNodeId': json['toNodeId'],
        'entitySeed': json['entitySeed'],
        'entityHash': json['entityHash'],
        'reportedHash': json['reportedHash'],
        'iterations': json['iterations'],
        'downloadTime': json['downloadTime'],
        'entityValid': json['entityValid'],
        'round': json['round'],
        'speed': json['speed'],
        'createdAt': json['createdAt'],
    };
}

export function BandwidthResultDTOToJSON(value?: BandwidthResultDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'fromNodeId': value.fromNodeId,
        'toNodeId': value.toNodeId,
        'entitySeed': value.entitySeed,
        'entityHash': value.entityHash,
        'reportedHash': value.reportedHash,
        'iterations': value.iterations,
        'downloadTime': value.downloadTime,
        'entityValid': value.entityValid,
        'round': value.round,
        'speed': value.speed,
        'createdAt': value.createdAt,
    };
}


