/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainHeightResultDTO
 */
export interface ChainHeightResultDTO {
    /**
     * ID of the test result
     * @type {string}
     * @memberof ChainHeightResultDTO
     */
    id: string;
    /**
     * ID of the tested node
     * @type {string}
     * @memberof ChainHeightResultDTO
     */
    nodeId: string;
    /**
     * 
     * @type {number}
     * @memberof ChainHeightResultDTO
     */
    expectedHeight: number;
    /**
     * 
     * @type {number}
     * @memberof ChainHeightResultDTO
     */
    reportedHeight: number;
    /**
     * 
     * @type {number}
     * @memberof ChainHeightResultDTO
     */
    round: number;
    /**
     * 
     * @type {boolean}
     * @memberof ChainHeightResultDTO
     */
    resultValid: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ChainHeightResultDTO
     */
    createdAt: Date;
}

export function ChainHeightResultDTOFromJSON(json: any): ChainHeightResultDTO {
    return ChainHeightResultDTOFromJSONTyped(json, false);
}

export function ChainHeightResultDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainHeightResultDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nodeId': json['nodeId'],
        'expectedHeight': json['expectedHeight'],
        'reportedHeight': json['reportedHeight'],
        'round': json['round'],
        'resultValid': json['resultValid'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ChainHeightResultDTOToJSON(value?: ChainHeightResultDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'nodeId': value.nodeId,
        'expectedHeight': value.expectedHeight,
        'reportedHeight': value.reportedHeight,
        'round': value.round,
        'resultValid': value.resultValid,
        'createdAt': (value.createdAt.toISOString()),
    };
}


