/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoLocationDTO
 */
export interface GeoLocationDTO {
    /**
     * latitude of the node's location
     * @type {number}
     * @memberof GeoLocationDTO
     */
    latitude: number;
    /**
     * longitude of the node's location
     * @type {number}
     * @memberof GeoLocationDTO
     */
    longitude: number;
}

export function GeoLocationDTOFromJSON(json: any): GeoLocationDTO {
    return GeoLocationDTOFromJSONTyped(json, false);
}

export function GeoLocationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoLocationDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function GeoLocationDTOToJSON(value?: GeoLocationDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latitude': value.latitude,
        'longitude': value.longitude,
    };
}


