/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthDTO
 */
export interface HealthDTO {
    /**
     * 
     * @type {string}
     * @memberof HealthDTO
     */
    status: string;
}

export function HealthDTOFromJSON(json: any): HealthDTO {
    return HealthDTOFromJSONTyped(json, false);
}

export function HealthDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function HealthDTOToJSON(value?: HealthDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}


