/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PingResultDTO,
    PingResultDTOFromJSON,
    PingResultDTOFromJSONTyped,
    PingResultDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface NodePingResultDTO
 */
export interface NodePingResultDTO {
    /**
     * ID of the test result
     * @type {string}
     * @memberof NodePingResultDTO
     */
    id: string;
    /**
     * ID of the tested node
     * @type {string}
     * @memberof NodePingResultDTO
     */
    nodeId: string;
    /**
     * 
     * @type {Array<PingResultDTO>}
     * @memberof NodePingResultDTO
     */
    pingResults: Array<PingResultDTO>;
    /**
     * 
     * @type {number}
     * @memberof NodePingResultDTO
     */
    averageTime: number;
    /**
     * 
     * @type {number}
     * @memberof NodePingResultDTO
     */
    round: number;
    /**
     * 
     * @type {boolean}
     * @memberof NodePingResultDTO
     */
    resultValid: boolean;
    /**
     * 
     * @type {Date}
     * @memberof NodePingResultDTO
     */
    createdAt: Date;
}

export function NodePingResultDTOFromJSON(json: any): NodePingResultDTO {
    return NodePingResultDTOFromJSONTyped(json, false);
}

export function NodePingResultDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodePingResultDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nodeId': json['nodeId'],
        'pingResults': ((json['pingResults'] as Array<any>).map(PingResultDTOFromJSON)),
        'averageTime': json['averageTime'],
        'round': json['round'],
        'resultValid': json['resultValid'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function NodePingResultDTOToJSON(value?: NodePingResultDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'nodeId': value.nodeId,
        'pingResults': ((value.pingResults as Array<any>).map(PingResultDTOToJSON)),
        'averageTime': value.averageTime,
        'round': value.round,
        'resultValid': value.resultValid,
        'createdAt': (value.createdAt.toISOString()),
    };
}


