/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Indicates the status of the current host.
* ``OK`` - node is going well
* ``FAIL`` - node has failed last test.
* ``INITIAL`` - node hasn't run any test yet.

 * @export
 * @enum {string}
 */
export enum NodeStatusDTO {
    OK = 'OK',
    FAIL = 'FAIL',
    INITIAL = 'INITIAL'
}

export function NodeStatusDTOFromJSON(json: any): NodeStatusDTO {
    return NodeStatusDTOFromJSONTyped(json, false);
}

export function NodeStatusDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeStatusDTO {
    return json as NodeStatusDTO;
}

export function NodeStatusDTOToJSON(value?: NodeStatusDTO | null): any {
    return value as any;
}

