/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeVersionResultDTO
 */
export interface NodeVersionResultDTO {
    /**
     * ID of the test result
     * @type {string}
     * @memberof NodeVersionResultDTO
     */
    id: string;
    /**
     * ID of the tested node
     * @type {string}
     * @memberof NodeVersionResultDTO
     */
    nodeId: string;
    /**
     * 
     * @type {number}
     * @memberof NodeVersionResultDTO
     */
    expectedNodeVersion: number;
    /**
     * 
     * @type {number}
     * @memberof NodeVersionResultDTO
     */
    reportedNodeVersion: number;
    /**
     * 
     * @type {number}
     * @memberof NodeVersionResultDTO
     */
    round: number;
    /**
     * 
     * @type {boolean}
     * @memberof NodeVersionResultDTO
     */
    resultValid: boolean;
    /**
     * 
     * @type {string}
     * @memberof NodeVersionResultDTO
     */
    createdAt: string;
}

export function NodeVersionResultDTOFromJSON(json: any): NodeVersionResultDTO {
    return NodeVersionResultDTOFromJSONTyped(json, false);
}

export function NodeVersionResultDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeVersionResultDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nodeId': json['nodeId'],
        'expectedNodeVersion': json['expectedNodeVersion'],
        'reportedNodeVersion': json['reportedNodeVersion'],
        'round': json['round'],
        'resultValid': json['resultValid'],
        'createdAt': json['createdAt'],
    };
}

export function NodeVersionResultDTOToJSON(value?: NodeVersionResultDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'nodeId': value.nodeId,
        'expectedNodeVersion': value.expectedNodeVersion,
        'reportedNodeVersion': value.reportedNodeVersion,
        'round': value.round,
        'resultValid': value.resultValid,
        'createdAt': value.createdAt,
    };
}


