/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Indicates how to sort the results:
* ``asc`` - ascending
* ``desc`` - descending

 * @export
 * @enum {string}
 */
export enum OrderDTO {
    Asc = 'asc',
    Desc = 'desc'
}

export function OrderDTOFromJSON(json: any): OrderDTO {
    return OrderDTOFromJSONTyped(json, false);
}

export function OrderDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDTO {
    return json as OrderDTO;
}

export function OrderDTOToJSON(value?: OrderDTO | null): any {
    return value as any;
}

