/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PingResultDTO
 */
export interface PingResultDTO {
    /**
     * ID of the tested node
     * @type {string}
     * @memberof PingResultDTO
     */
    toNodeId: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof PingResultDTO
     */
    samples: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof PingResultDTO
     */
    averageTime: number;
    /**
     * 
     * @type {boolean}
     * @memberof PingResultDTO
     */
    resultValid: boolean;
}

export function PingResultDTOFromJSON(json: any): PingResultDTO {
    return PingResultDTOFromJSONTyped(json, false);
}

export function PingResultDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PingResultDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'toNodeId': json['toNodeId'],
        'samples': json['samples'],
        'averageTime': json['averageTime'],
        'resultValid': json['resultValid'],
    };
}

export function PingResultDTOToJSON(value?: PingResultDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'toNodeId': value.toNodeId,
        'samples': value.samples,
        'averageTime': value.averageTime,
        'resultValid': value.resultValid,
    };
}


