/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsivenessResultDTO
 */
export interface ResponsivenessResultDTO {
    /**
     * ID of the test result
     * @type {string}
     * @memberof ResponsivenessResultDTO
     */
    id: string;
    /**
     * ID of the tested node
     * @type {string}
     * @memberof ResponsivenessResultDTO
     */
    nodeId: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsivenessResultDTO
     */
    numRequests: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsivenessResultDTO
     */
    numResponses: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsivenessResultDTO
     */
    totalTime: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsivenessResultDTO
     */
    round: number;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsivenessResultDTO
     */
    resultValid: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ResponsivenessResultDTO
     */
    createdAt: Date;
}

export function ResponsivenessResultDTOFromJSON(json: any): ResponsivenessResultDTO {
    return ResponsivenessResultDTOFromJSONTyped(json, false);
}

export function ResponsivenessResultDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsivenessResultDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nodeId': json['nodeId'],
        'numRequests': json['numRequests'],
        'numResponses': json['numResponses'],
        'totalTime': json['totalTime'],
        'round': json['round'],
        'resultValid': json['resultValid'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ResponsivenessResultDTOToJSON(value?: ResponsivenessResultDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'nodeId': value.nodeId,
        'numRequests': value.numRequests,
        'numResponses': value.numResponses,
        'totalTime': value.totalTime,
        'round': value.round,
        'resultValid': value.resultValid,
        'createdAt': (value.createdAt.toISOString()),
    };
}


