/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BandwidthResultDTO,
    BandwidthResultDTOFromJSON,
    BandwidthResultDTOFromJSONTyped,
    BandwidthResultDTOToJSON,
    ChainHeightResultDTO,
    ChainHeightResultDTOFromJSON,
    ChainHeightResultDTOFromJSONTyped,
    ChainHeightResultDTOToJSON,
    ChainPartResultDTO,
    ChainPartResultDTOFromJSON,
    ChainPartResultDTOFromJSONTyped,
    ChainPartResultDTOToJSON,
    ComputingPowerResultDTO,
    ComputingPowerResultDTOFromJSON,
    ComputingPowerResultDTOFromJSONTyped,
    ComputingPowerResultDTOToJSON,
    NodeBalanceResultDTO,
    NodeBalanceResultDTOFromJSON,
    NodeBalanceResultDTOFromJSONTyped,
    NodeBalanceResultDTOToJSON,
    NodeVersionResultDTO,
    NodeVersionResultDTOFromJSON,
    NodeVersionResultDTOFromJSONTyped,
    NodeVersionResultDTOToJSON,
    PingResultDTO,
    PingResultDTOFromJSON,
    PingResultDTOFromJSONTyped,
    PingResultDTOToJSON,
    ResponsivenessResultDTO,
    ResponsivenessResultDTOFromJSON,
    ResponsivenessResultDTOFromJSONTyped,
    ResponsivenessResultDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface TestResultInfoDTO
 */
export interface TestResultInfoDTO {
    /**
     * 
     * @type {BandwidthResultDTO}
     * @memberof TestResultInfoDTO
     */
    bandwidthResult: BandwidthResultDTO;
    /**
     * 
     * @type {ChainHeightResultDTO}
     * @memberof TestResultInfoDTO
     */
    chainHeightResult: ChainHeightResultDTO;
    /**
     * 
     * @type {ChainPartResultDTO}
     * @memberof TestResultInfoDTO
     */
    chainPartResult: ChainPartResultDTO;
    /**
     * 
     * @type {ComputingPowerResultDTO}
     * @memberof TestResultInfoDTO
     */
    computingPowerResult: ComputingPowerResultDTO;
    /**
     * 
     * @type {NodeBalanceResultDTO}
     * @memberof TestResultInfoDTO
     */
    nodeBalanceResult: NodeBalanceResultDTO;
    /**
     * 
     * @type {NodeVersionResultDTO}
     * @memberof TestResultInfoDTO
     */
    nodeVersionResult: NodeVersionResultDTO;
    /**
     * 
     * @type {PingResultDTO}
     * @memberof TestResultInfoDTO
     */
    pingResult: PingResultDTO;
    /**
     * 
     * @type {ResponsivenessResultDTO}
     * @memberof TestResultInfoDTO
     */
    responsivenessResult: ResponsivenessResultDTO;
}

export function TestResultInfoDTOFromJSON(json: any): TestResultInfoDTO {
    return TestResultInfoDTOFromJSONTyped(json, false);
}

export function TestResultInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestResultInfoDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bandwidthResult': BandwidthResultDTOFromJSON(json['bandwidthResult']),
        'chainHeightResult': ChainHeightResultDTOFromJSON(json['chainHeightResult']),
        'chainPartResult': ChainPartResultDTOFromJSON(json['chainPartResult']),
        'computingPowerResult': ComputingPowerResultDTOFromJSON(json['computingPowerResult']),
        'nodeBalanceResult': NodeBalanceResultDTOFromJSON(json['nodeBalanceResult']),
        'nodeVersionResult': NodeVersionResultDTOFromJSON(json['nodeVersionResult']),
        'pingResult': PingResultDTOFromJSON(json['pingResult']),
        'responsivenessResult': ResponsivenessResultDTOFromJSON(json['responsivenessResult']),
    };
}

export function TestResultInfoDTOToJSON(value?: TestResultInfoDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bandwidthResult': BandwidthResultDTOToJSON(value.bandwidthResult),
        'chainHeightResult': ChainHeightResultDTOToJSON(value.chainHeightResult),
        'chainPartResult': ChainPartResultDTOToJSON(value.chainPartResult),
        'computingPowerResult': ComputingPowerResultDTOToJSON(value.computingPowerResult),
        'nodeBalanceResult': NodeBalanceResultDTOToJSON(value.nodeBalanceResult),
        'nodeVersionResult': NodeVersionResultDTOToJSON(value.nodeVersionResult),
        'pingResult': PingResultDTOToJSON(value.pingResult),
        'responsivenessResult': ResponsivenessResultDTOToJSON(value.responsivenessResult),
    };
}


