/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ChainHeightResultDTO,
    ChainHeightResultDTOFromJSON,
    ChainHeightResultDTOFromJSONTyped,
    ChainHeightResultDTOToJSON,
    ChainPartResultDTO,
    ChainPartResultDTOFromJSON,
    ChainPartResultDTOFromJSONTyped,
    ChainPartResultDTOToJSON,
    ComputingPowerResultDTO,
    ComputingPowerResultDTOFromJSON,
    ComputingPowerResultDTOFromJSONTyped,
    ComputingPowerResultDTOToJSON,
    NodeBalanceResultDTO,
    NodeBalanceResultDTOFromJSON,
    NodeBalanceResultDTOFromJSONTyped,
    NodeBalanceResultDTOToJSON,
    NodeBandwidthResultDTO,
    NodeBandwidthResultDTOFromJSON,
    NodeBandwidthResultDTOFromJSONTyped,
    NodeBandwidthResultDTOToJSON,
    NodePingResultDTO,
    NodePingResultDTOFromJSON,
    NodePingResultDTOFromJSONTyped,
    NodePingResultDTOToJSON,
    NodeVersionResultDTO,
    NodeVersionResultDTOFromJSON,
    NodeVersionResultDTOFromJSONTyped,
    NodeVersionResultDTOToJSON,
    ResponsivenessResultDTO,
    ResponsivenessResultDTOFromJSON,
    ResponsivenessResultDTOFromJSONTyped,
    ResponsivenessResultDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface TestResultInfoDTO
 */
export interface TestResultInfoDTO {
    /**
     * 
     * @type {NodeBandwidthResultDTO}
     * @memberof TestResultInfoDTO
     */
    nodeBandwidthResult?: NodeBandwidthResultDTO;
    /**
     * 
     * @type {ChainHeightResultDTO}
     * @memberof TestResultInfoDTO
     */
    chainHeightResult?: ChainHeightResultDTO;
    /**
     * 
     * @type {ChainPartResultDTO}
     * @memberof TestResultInfoDTO
     */
    chainPartResult?: ChainPartResultDTO;
    /**
     * 
     * @type {ComputingPowerResultDTO}
     * @memberof TestResultInfoDTO
     */
    computingPowerResult?: ComputingPowerResultDTO;
    /**
     * 
     * @type {NodeBalanceResultDTO}
     * @memberof TestResultInfoDTO
     */
    nodeBalanceResult?: NodeBalanceResultDTO;
    /**
     * 
     * @type {NodeVersionResultDTO}
     * @memberof TestResultInfoDTO
     */
    nodeVersionResult?: NodeVersionResultDTO;
    /**
     * 
     * @type {NodePingResultDTO}
     * @memberof TestResultInfoDTO
     */
    nodePingResult?: NodePingResultDTO;
    /**
     * 
     * @type {ResponsivenessResultDTO}
     * @memberof TestResultInfoDTO
     */
    responsivenessResult?: ResponsivenessResultDTO;
}

export function TestResultInfoDTOFromJSON(json: any): TestResultInfoDTO {
    return TestResultInfoDTOFromJSONTyped(json, false);
}

export function TestResultInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestResultInfoDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nodeBandwidthResult': !exists(json, 'nodeBandwidthResult') ? undefined : NodeBandwidthResultDTOFromJSON(json['nodeBandwidthResult']),
        'chainHeightResult': !exists(json, 'chainHeightResult') ? undefined : ChainHeightResultDTOFromJSON(json['chainHeightResult']),
        'chainPartResult': !exists(json, 'chainPartResult') ? undefined : ChainPartResultDTOFromJSON(json['chainPartResult']),
        'computingPowerResult': !exists(json, 'computingPowerResult') ? undefined : ComputingPowerResultDTOFromJSON(json['computingPowerResult']),
        'nodeBalanceResult': !exists(json, 'nodeBalanceResult') ? undefined : NodeBalanceResultDTOFromJSON(json['nodeBalanceResult']),
        'nodeVersionResult': !exists(json, 'nodeVersionResult') ? undefined : NodeVersionResultDTOFromJSON(json['nodeVersionResult']),
        'nodePingResult': !exists(json, 'nodePingResult') ? undefined : NodePingResultDTOFromJSON(json['nodePingResult']),
        'responsivenessResult': !exists(json, 'responsivenessResult') ? undefined : ResponsivenessResultDTOFromJSON(json['responsivenessResult']),
    };
}

export function TestResultInfoDTOToJSON(value?: TestResultInfoDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nodeBandwidthResult': NodeBandwidthResultDTOToJSON(value.nodeBandwidthResult),
        'chainHeightResult': ChainHeightResultDTOToJSON(value.chainHeightResult),
        'chainPartResult': ChainPartResultDTOToJSON(value.chainPartResult),
        'computingPowerResult': ComputingPowerResultDTOToJSON(value.computingPowerResult),
        'nodeBalanceResult': NodeBalanceResultDTOToJSON(value.nodeBalanceResult),
        'nodeVersionResult': NodeVersionResultDTOToJSON(value.nodeVersionResult),
        'nodePingResult': NodePingResultDTOToJSON(value.nodePingResult),
        'responsivenessResult': ResponsivenessResultDTOToJSON(value.responsivenessResult),
    };
}


