/* tslint:disable */
/* eslint-disable */
/**
 * Symbol Node Rewards API
 * The API is the rest gateway to the symbol rewards controller.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Indicates the status a test
* ``INITIAL`` - Hasn't run yet
* ``DISABLED`` - Test is disabled.
* ``SUCCEEDED`` - Test has succesed
* ``FAILED`` - Test has failed
* ``ERROR`` - Test has been an error running the test.

 * @export
 * @enum {string}
 */
export enum TestResultStatusDTO {
    INITIAL = 'INITIAL',
    DISABLED = 'DISABLED',
    SUCCEEDED = 'SUCCEEDED',
    FAILED = 'FAILED',
    ERROR = 'ERROR'
}

export function TestResultStatusDTOFromJSON(json: any): TestResultStatusDTO {
    return TestResultStatusDTOFromJSONTyped(json, false);
}

export function TestResultStatusDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestResultStatusDTO {
    return json as TestResultStatusDTO;
}

export function TestResultStatusDTOToJSON(value?: TestResultStatusDTO | null): any {
    return value as any;
}

